controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# handle error page for not found routes (in prod env)
when@prod:
    catch_all:
        path: /{any}
        controller: App\Controller\ErrorController::errorHandle404
        methods: ['GET']
        requirements:
            any: .*
